# Generated by Django 6.0.7 on 2026-07-25 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policealert',
            name='escalated_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_alerts', to='police.policezone'),
        ),
        migrations.AddField(
            model_name='policealert',
            name='is_escalated',
            field=models.BooleanField(default=False),
        ),
    ]
